apiVersion: v1
kind: Service
metadata:
  name: homer
  labels:
    app.kubernetes.io/name: homer
    app.kubernetes.io/part-of: platform
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: homer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
