{{- range $name, $cfg := .Values.kubernetesAuthRoles }}
---
apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: {{ $name | quote }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: vault-config
spec:
  forProvider:
    backend: {{ $cfg.backend | quote }}
    roleName: {{ $name | quote }}
    boundServiceAccountNames:
      {{- range $cfg.boundServiceAccountNames }}
      - {{ . | quote }}
      {{- end }}
    boundServiceAccountNamespaces:
      {{- range $cfg.boundServiceAccountNamespaces }}
      - {{ . | quote }}
      {{- end }}
    tokenPolicies:
      {{- range $cfg.tokenPolicies }}
      - {{ . | quote }}
      {{- end }}
    tokenTtl: {{ $cfg.tokenTtl }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef.name | quote }}
{{- end }}
