{{- range $name, $cfg := .Values.policies }}
---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: {{ $name | quote }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: vault-config
spec:
  forProvider:
    name: {{ $name | quote }}
    policy: |-
{{ $cfg.hcl | indent 6 }}
  providerConfigRef:
    name: {{ $.Values.providerConfigRef.name | quote }}
{{- end }}
